### ISSUE TITLE
buildDictionary requires GHC > 7.6 but is used anyway in GHC ≤ 7.6

### ISSUE THREAD

**Issue by RyanGlScott** [ku-fpg/hermit#97]
As of commit 98c47f8ba836fd9c041436735a28ee674ee5c317, <tt>HERMIT.GHC</tt> exports the <tt>buildDictionary</tt> command <a href="https://github.com/ku-fpg/hermit/blob/master/src/HERMIT/GHC.hs#L48">only if GHC > 7.6 is used</a>, but <tt>HERMIT.Dictionary.Reasoning</tt> uses <tt>buildDictionary</tt> <a href="https://github.com/ku-fpg/hermit/blob/master/src/HERMIT/Dictionary/Reasoning.hs#L277">without any kind of GHC version checking</a>, causing HERMIT to fail to compile on GHC ≤ 7.6:

```
[35 of 66] Compiling HERMIT.Dictionary.Reasoning ( src/HERMIT/Dictionary/Reasoning.hs, dist/build/HERMIT/Dictionary/Reasoning.o )

src/HERMIT/Dictionary/Reasoning.hs:277:37:
    Not in scope: `buildDictionary'
```
